on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Integração Contínua
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test

  cd:
    name: Deploy Contínuo
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Sucesso no CI
        run: echo "Deploying..."
